### ISSUE TITLE
Wake-up screen not working

### ISSUE THREAD

**Issue by JeremySavonet** [iofermento/Hackintosh-i7-10700-Gigabyte-z490-Vision-G#1]
Hello,

I've fixed the issue with the screen after sleep/wake-up:
FIXED BY ADDING BOOT-ARGS: igfxonln=1

If you'r interested in ;)

Kind regards

**Comment by ferrarafer** [comment]
hohoho I thought I had tested that boot argument... it works !! Thank you!! :fire: :raised_hands: Was the repository useful for you?

**Comment by iofermento** [comment]
hohoho I thought I had tested that boot argument... it works !! Thank you!! 🔥 🙌
Was the repository useful for you?
